spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

chank-size: 5
page-size: 10