
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    show_sql: true
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql